#! /bin/bash
# link: ~/.config/bspwm/bspwmrc
# code: language=sh


# paddings for the bar and other
# bspc config top_padding 0
# bspc config bottom_padding 0

# monocle
bspc config borderless_monocle   false
bspc config single_monocle       true
bspc config gapless_monocle      false

# other
bspc monitor -d 1 2 3 4
bspc config border_width 1
bspc config window_gap 16
bspc config normal_border_color "#74737f"
bspc config focused_border_color "#F4F3Ff"
bspc config focus_follows_pointer true