// adresses shorts
:wiki: https://w.wiki/


*on english → link:../../readme.adoc[`../../readme.adoc`]*

|===

| я пишу… | принципы в личных проектах

| 

*на {wiki}9VuF[`go`]*. в 10 лет моим первым языком был {wiki}35Gx[`c++`], от
чего динамическое типизирование мне стало в принципе непривычным. и ни {wiki}PoF[`python`], ни
{wiki}5WMt[`typescript`], с косметическими типами мн не зашли. также писал на
{wiki}8yNr[`haskell`], {wiki}9VuP[`ruby`], {wiki}9VuT[`raku`], и других, трудно вспоминаемых.

*для {wiki}S5C[`linux`]*. в те же года, моё желание взломать wi-fi совпало с
новым предприятием отца: обучение программированию подростков на thinkpad-ах с
{wiki}9VvY[`lubuntu`]. один из них взял себе с исследоал {wiki}9VuS[`debian`],
{wiki}5kfD[`opensuse`], {wiki}9VuV[`arch`], {wiki}7caP[`fedora`], и другие.

*в {wiki}3oas[`vscode`]*, так как он универсальнее и проще
{wiki}PoB[`vim`].

|

*строчные логи и комменты*: прописные буквы не играют роли в грамматике,
завершает предложение точка. иконка этого минускулизма — 🔡, а маюскулизма — 🔠.

*рассокращение названий директорий* чтобы сформировать единообразную файловую
структуру, где
`./internal` и `./pkg` или `./cmd` под одной крышей, я пишу их полную форму, типа
`./packages` и `./commands`. с автодополнением и аббревиатурами внутри оболочки
исполнения, смысла в этих сокращениях — нет.

|===


== читайте далее

- link:autobio.adoc[автобиография] 
- https://registry.jsonresume.org/zaboal[резюме на json]