#! /bin/bash

# link: ~/.config/bspwm/bspwmrc


# paddings for the bar and other
bspc config top_padding 16
bspc config bottom_padding 3

# monocle
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config gapless_monocle      true

# rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# other
bspc monitor -d i ii iii iv v
bspc config border_width 1
bspc config window_gap 0
bspc config focused_border_color "#FFFFFF"
bspc config split_ratio          0.52
