#! /bin/fish
# link: ~/.config/bspwm/lemonbar.sh


function _date
      echo (date +"%m-%d %H:%M")
end

set interface wlp169s0
function _connection
      echo (nmcli -t -f name,device connection show --active | grep $interface | cut -d\: -f1)
end

set battery /sys/class/power_supply/BAT0
function _battery
      if test (cat $battery/status) = "Charging" 
            echo (cat $battery/capacity)%+
      else
            echo (cat $battery/capacity)%-
      end
end

function _volume
      echo (amixer sget Master | grep 'Right:' | awk -F'[][]' '{ print $2 }')
end

function _workspace
      echo (xprop -root _NET_CURRENT_DESKTOP | awk '{print $3+1}')
end


while true
        echo "%{l}   $(_workspace) \
              %{c}$(_date) \
              %{r}$(_connection)  $(_volume)  $(_battery)   "
end