#! /bin/bash
# link: ~/.xinitrc

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources
xrandr --output eDP-1 --mode 1280x720   # hd resoltion

xsetroot -solid "#34333f" &             # dark-grey wallpaper

sxhkd &     		                    # hotkeys daemon
polybar &   		                    # status bar

exec bspwm                              # finish with starting the wm
