== родился 15 января 2007 года

18 и 19 летние байко ирина и зажигин алексей в мурманске 15 просинца ‘07 года,
на две недели позже, нарекли меня богданом. она занялась писательством, а он
предпринимательством. спустя 3 года они развелись сохраняя связь, жил в основном
у мамы. записали в «а» класс 36-й школы; и ‘15 года мать вновь обвенчалась:
горенюк александр стал мне отчимом, и я обрёл молочного брата — артёма.


== программист, предприниматель и писатель

ютьюб срекомендовал ролики о хакерстве: чтобы взломать вай-фай понадобился
кали-линукс, который не мог поставить на единственный компьютер. к счастью, отец
франчизируя «алгоритмику» закупил финк-пады на лубунте, и позволил один забрать.
сбрасывая пароль рута испробовал опен-сьюз, дебиан, манджаро, федору и арч;
параллельно писал в виме на голанге, питоне, тайпксрипте и других.

как освоил линукс, нарисовал в инкскейпе логотип для организации международной
конституции; руководствуясь у мамы книге «пиши и сокращай» написал агитку:
читателю понравилось; и я подружился с [инкогнито], который научил системному
администрированию и предоставил сервера для мини-государства, юридической
энциклопедии, художественного издательства, веб-студии, биоинженерной компании,
ксго команды и другого; но без финансирования всё было заморожено.

меж тем изучил эсператно, и заинтересовался ложбаном: нарисовал логотип их
дискорд сервера, форматировал содержание «эталонной грамматики» и рбнф. для себя
решил вести лог в телеграмме, писать минускулом и транслитерировать
заимствования.


== переселились в санкт-петербург

за день до вылета вспылил в вайбере на мурманских одноклассников. арендовали
квартиру у звёздной, перевели в «а» класс 519-й школы, переехали в другую съёмку
у фрунзенской. стал администрировать классный ватсап и общешкольный телеграм.

сдал огэ, и, чтобы в конечном счёте поступить на госфак для гражданской службы
вместо военной, зачислился на 10 класс той же школы.