name: sync-the-fields

on: 
  push

jobs:
  sync-the-fields:
    name: sync the fields in my profiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: 'fields' 
          sparse-checkout-cone-mode: false
      - name: sync bio
        run: |
          ls -lah
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/user \
          -d "{\"bio\": \"$(<fields/bio)\"}"